-- Revenue over time analysis
select 
year(timestamp) as order_year,
sum(gross_revenue) as total_sales,
count(distinct customer_id) as total_customers,
sum(quantity) as total_quantity
from transactions
group by year(timestamp)
order by year(timestamp);

select
     date_trunc('month', timestamp) as month,
     sum(gross_revenue) as revenue
from transactions
group by month
order by month;

-- Revenue by loyalty-tier
select 
      c.loyalty_tier,
      sum(t.gross_revenue) as total_revenue,
      count(distinct t.transaction_id) as transactions_made,
      count(distinct t.customer_id) as paying_customers,
      round(sum(t.gross_revenue) / count(distinct t.transaction_id) , 2) as avg_order_value,
      round(sum(t.gross_revenue) / count(distinct t.customer_id) , 2) as revenue_per_customer
from transactions t
join customers c
on t.customer_id = c.customer_id
group by c.loyalty_tier
order by total_revenue desc;

-- Bronze customers contribute the highest total revenue due to large customer base and high transactions volume.
-- However high loyalty tiers (silver, gold, platinum) exhibit increasing revenue per customer.

-- customers with refunds
select count(*) as customers_with_refunds
from vw_customer_features
where total_revenue<0;

-- customers with refunds based on loyalty tier
select loyalty_tier, count(*) as customers_with_refunds
from vw_customer_features
where total_revenue<0
group by loyalty_tier;

-- revenue generated by product category
select 
    p.product_id, p.category,
     e.experiment_group,
    sum(t.gross_revenue) as revenue
from transactions t
join events e
 on t.customer_id = e.customer_id
join products p
  on p.product_id = e.product_id
group by  p.product_id, p.category, e.experiment_group
order by revenue desc;

-- refunds by product category
select 
     p.category,
    count(*) as refunded_transactions,
    sum(t.gross_revenue) as total_revenue_value
from transactions t
join products p
on p.product_id = t.product_id
where gross_revenue < 0
group by p.category
order by refunded_transactions desc, total_revenue_value desc;

-- Discounts per product category
select 
     p.category,
    count(*) as discount_provided,
    avg(t.discount_applied) as avg_discount
from transactions t
join products p
on p.product_id = t.product_id
where discount_applied > 0
group by p.category
order by discount_provided desc, avg_discount desc;

